### PR TITLE
Remove album from details in Discord Rich Presence

### PR DESCRIPTION
**Pull request by clavierpaul**
The album name is arguably the least important part of the song description, yet in the current implementation it comes before artist. This often causes text clipping in discord, hiding the artist name whilst showing the album it's on.

This also works better for singles, as the name of the song is duplicated in the current implementation (as album name == song name). Overall, it's simply a cleaner way of displaying song info.

A surprisingly common example below:
image

Notice how Everchanging is duplicated top and bottom, and Haywyre (the artist) is only visible by the letter "H"

Instead, why not display it like this?
image

### CODE REVIEW

**Comment by jostrander** [comment]
Personally I prefer this view of the existing one, so LGTM. It seems to be the general consensus in #2978 as well.

**Comment by Evanito** [comment]
When is this going to be put into a release?

**Comment by simoniz0r** [comment]
I'd be up for a new release just for this, tbh lol... the current layout is kinda not great haha

**Comment by clavierpaul** [comment]
If you download one of the build artifacts the change is there, that's what I've done.

**Pull request merged**
