### PR TITLE
Switch control bar to Vectors

### PR DESCRIPTION
**Pull request by O-Dog5960**

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Where did the SVG code come from?

**Comment by O-Dog5960** [comment]
I made it with Affinity Designer. I took the PNG's and traced it with pen tool and curves tool and exported as an SVG file for web.

**Comment by MarshallOfSound** [comment]
@O-Dog5960 I totally appreciate the effort (and sorry but I can't see that email 😆 ).  But I totally have the original SVG's from https://design.google.com/icons/

**Comment by O-Dog5960** [comment]
*facepalm* OF COURSE

**Pull request closed without merging**
