### PR TITLE
Add Georgian locale

### PR DESCRIPTION
**Pull request by akalongman**

### CODE REVIEW

**Comment by akalongman** [comment]
Some tests failed because:
```
error An unexpected error occurred: "https://codeload.github.com/hydrabolt/discord.js/tar.gz/d46eec4da40c01d134d863b9421fbc12d2ec6d20: Request failed "404 Not Found"".
```

**Comment by MarshallOfSound** [comment]
@akalongman If you rebase onto latest master the CI should be green 👍

**Comment by akalongman** [comment]
@MarshallOfSound done, but there are still some errors

**Comment by MarshallOfSound** [comment]
@akalongman That's because you are missing some translation strings

```
1) Translations ka.json should have the same translation keys as en-US:
     AssertionError: expected { Object (audio-device-communications, audio-device-default, ...) } to have a property 'slack-token-label'
      at test/electron/translations_spec.js:57:32
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test/electron/translations_spec.js:56:20)
```

You can use `vendor/update-translations.js` to put the new empty strings in your file for you to fill in 👍

**Comment by akalongman** [comment]
@MarshallOfSound I've run `yarn test` and there are no errors, only warnings, but here tests are still failed

**Pull request merged**
