### PR TITLE
Support for macbook touchbar

### PR DESCRIPTION
**Pull request by th3dark0n3**
This adds support for touch bar in MacBook

Tested on MacBook Pro 2018

img_20190227_122422

---
This change is [Reviewable](https://reviewable.io/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/3505)

### CODE REVIEW

**Comment by th3dark0n3** [comment]
Forgot to raise a feature request first, should I still raise it?

**Comment by MarshallOfSound** [comment]
@th3dark0n3 Can you remove the slider (it doesn't look that great IMO and the native slider you get from `electron-media-sevice` is way better.  Also can you update the thumbs up / down buttons to be the material icons for thumbs up / down instead of the emojis 👍

**Comment by th3dark0n3** [comment]
@MarshallOfSound changed, implemented like/dislike similar to app, i.e., fill when liked
Not sure what to do about the codeclimate issue, the code looks more readable when keeping the changes

**Comment by th3dark0n3** [comment]
Yup I saw the PR in Electron
Let me know if I need to update this PR?

**Comment by arongeorgel** [comment]
Will this contain the changes for integrating the media button while one is in another app like Spotify has it? (check images bellow)
IMG_20190412_144752
IMG_20190412_144808

**Pull request merged**
