### PR TITLE
Removed "features" that the official client has

### PR DESCRIPTION
**Pull request by blha303**
Also your project name is too long. Abbreviation is great.

(I was shown this project by a guy who's ranting about it, I'm bringing him down a peg)

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
> (I was shown this project by a guy who's ranting about it, I'm bringing him down a peg)

That's all very well but each of these features required implementation code inside this player, regardless of your opinion of the player the feature list is accurate.

**Comment by blha303** [comment]
Thank you for humoring me, have a good day.

**Comment by MarshallOfSound** [comment]
For future reference, at least in my opinion this kind of PR violates the open source code of conduct and is not looked upon favorably

**Comment by blha303** [comment]
Duly noted, thank you.

**Pull request closed without merging**
