### PR TITLE
Fix Segfault on Ubuntu 18.10. Fixes 3391#

### LINKED ISSUE #3391: Doesn't open on ubuntu 18.10
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Ubuntu 18.10

**GPMDP Version:** 4.6.1
 
**Issue Descriptions:**
App doesn't open whatsoever. When I run via command line, I get:
```
[1]    9872 segmentation fault (core dumped)  google-play-music-desktop-player

~  
```
It worked fine on ubuntu 18.04, but not on 18.10 (tried on two different computers, sent a crash report from one).
**Steps to Reproduce:**
Install on ubuntu 18.10
Try to open it.

Thanks for your help!

P.S. It seems similar to #3117, but libgconf-2-4 was already installed.

### PR DESCRIPTION
**Pull request by zerkz**
Fixes #3391 

- Upgrade Electron to 2.0.8 (solves https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1790966)
- Upgrade discord presence module to 0.7. 0.5 was 404ing when getting the dependency. you can see this in previous test runs/etc. Not sure what's up.
- Built/tested using node 9.4.0 (same node as gpmdp/build-64 image)
- Adds `-` instead of spaces in the product name, to get rid of node-gyp build warnings about having a `builddir` with spaces.

### CODE REVIEW

**Comment by jostrander** [comment]
Does the spaces change cause the packaging to build with dashes?

**Comment by zerkz** [comment]
@jostrander It does (pulls `productName` from package.json), but the installers seem unaffected (they use a different naming template). Dashes are legal in Windows filenames as well. 

Should the version be bumped for this by the way? Just realized I didn't do anything with that.

**Comment by jostrander** [comment]
No, versioning happens after it's pulled into master.

**Comment by zerkz** [comment]
@jostrander :+1: , let me know if I need to make any changes. 

It looks like the CircleCi Darwin tests have been failing for a bit - https://circleci.com/gh/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/2754

**Comment by zerkz** [comment]
@jostrander Good points. I was grasping at anything whenever I was debugging this, so definitely can be handled in another PR. I reverted the change with another commit.

**Comment by Steampunkery** [comment]
Thanks for the snappy fix! Could one of you compile the deb for 64 bit Ubuntu 18.10? I assume someone here has it given the thread. I would do it myself, but I'm not a node guy and I keep getting errors when I try. Funny part is I can `npm start` to run the app after building but I can't compile it.

**Comment by jostrander** [comment]
https://2838-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_amd64.deb

Not sure if this will work but this is the latest master as built by CI.

**Comment by zerkz** [comment]
@Steampunkery I have a deb built but I've been slapped on the wrists before for linking biniaries/etc (see https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3278#issuecomment-406201328)

@jostrander provided a good solution though!

**Comment by Steampunkery** [comment]
No, @jostrander that one is the broken one. It would seem that circleCI hasn't built the new version. But the tests passed so that's good.

**Comment by jostrander** [comment]
CircleCI has definitely built the new version:

https://circleci.com/gh/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/2838

This is the latest build on master, if you login to CircleCI you can view the artifacts tab where you can download the latest build. It's still labeled 4.6.1 because the package version hasn't been incremented for release.

image

**Comment by Steampunkery** [comment]
Wow thanks! I was looking for something like a downloads tab. As you can tell, I'm new to CircleCI

**Comment by christofdamian** [comment]
FYI: this problem also happens on Fedora 29, which will be released today.

**Pull request merged**
