### PR TITLE
test

### PR DESCRIPTION
**Pull request by JooooeJingGuo**
test

[Review on Reviewable](https://reviewable.io/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/313)

### CODE REVIEW

**Comment by tf2manu994** [comment]
what are you doing mate

test it in your own fork

`+testtesttest` does not a good pull request make

what the hell

**Comment by JooooeJingGuo** [comment]
sorry

**Comment by MarshallOfSound** [comment]
What the hell is this, test pull requests on the official github testing repository (there is one somewhere specifically for people to muck around with pull requests)

Please don't clutter my already cluttered activity feed

**Comment by MarshallOfSound** [comment]
Also the PR automatically triggers CI builds, these builds waste my time, the CI agents time and hold up more important jobs in the queue

**Pull request closed without merging**
