### PR TITLE
Fixing grammar in website

### PR DESCRIPTION
**Pull request by tf2manu994**
[Review on Reviewable](https://reviewable.io/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/317)

### CODE REVIEW

**Comment by tf2manu994** [comment]
can you disable ci on the website branch

**Comment by MarshallOfSound** [comment]
nah, its funny watching your builds fail :+1:

**Comment by MarshallOfSound** [comment]
These small PR's are becoming annoying (I like the enthusiasm) but can we try make one larger PR with lots of small grammar / styling fixes

:+1:

**Comment by tf2manu994** [comment]
@MarshallOfSound i just add them as i notice stuff wrong. dont know why you closed this though

**Comment by MarshallOfSound** [comment]
I know, I'm just saying please make sure that there isn't going to be "just one more" after this :+1: 

Go through a thourough check now if this is what you are doing

**Comment by tf2manu994** [comment]
okay, doing a thorough check now

**Comment by tf2manu994** [comment]
complete

**Comment by MightyPork** [comment]
@tf2manu994 I'd suggest you close those old bad PR's and leave only the final good one...

**Comment by MarshallOfSound** [comment]
Branch has conflicts @tf2manu994

**Pull request closed without merging**
