### PR TITLE
Updates and Fixes issues with Discord Rich Presences

### LINKED ISSUE #3266: Discord Rich Presences uses old logo
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
The Icon for the GPMDP Discord Rich Presences is still using the old Triangle Logo instead of the new Round logo!
image

### LINKED ISSUE #3404: DRPI stops working after Discord restart
**OS:** 
Win10 1803 17134.345

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
DRPI stops working after Discord restart
Requires GPMDP to be restarted for DRPI to work again

**Steps to Reproduce:**
1) Start Discord
2) Open GPMDP and Play song
3) Restart Discord
4) Observe

I think this can also be reprouced by putting the comptuer into sleep mode and waking it back up instead of restarting Discord

### PR DESCRIPTION
**Pull request by Nithindanday**
Possible fix to #2969
This issue was caused by a dead RPC connection when Discord wasn't open, still trying to send requests to it.

Fixes #3266
This is fixed by using my own Discord application instead of the currently used one. I've previously requested to join the Team for the existing one but haven't got a reply. I have this one setup for teams already, and willing to add people if I'm provided with a Discord username + Discrim.

Fixes #3404
A connect + disconnect event were needed to be able to check if the client was actually connected and when to check for reconnections for this.

Looking through the Basic Discord-rich-presneces library used before, there was no event triggered for disconnecting from client.
This is why I have instead replace it with the native discord-rpc library instead of the wrapper library originally used, for better control over the RPC + all of the events including the Disconnect.

I've also added an additional feature of showing a Heart icon on songs which are liked.

### CODE REVIEW

**Comment by Nithindanday** [comment]
Everything works merging the newest one, discord integration and artists both work

**Comment by Nithindanday** [comment]
test it [here](https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/builds/35801590/artifacts)

**Comment by jostrander** [comment]
This is just #3785?

**Comment by Alipoodle** [comment]
This is a Fork of my Repo 😆
The only differences is the ClientId used for the Discord RPC + Comment in the Read Me to download.

**Comment by Nithindanday** [comment]
> This is a Fork of my Repo 😆
> The only differences is the ClientId used for the Discord RPC + Comment in the Read Me to download.

lmaooo yes sorry, i needed appveyor to generate a new build because my stupid self wasnt able to build it properly.

**Pull request closed without merging**
