### PR TITLE
Initial gulp re-factoring for separate Linux builds.

### PR DESCRIPTION
**Pull request by jostrander**
Not even going to lie, I'm cheating and using this PR so CI will validate for all three build environments at once :+1:

Do not merge.

### CODE REVIEW

**Comment by jostrander** [comment]
@BrianAllred what works best for an AUR, the files straight out of the packager, or a deb/rpm? For example:

image

**Comment by MarshallOfSound** [comment]
@jostrander Just going to question the use of `asar`.  It has quite a few caveats that I believe would break our current usage of the `fs` module.

http://electron.atom.io/docs/v0.36.0/tutorial/application-packaging/#treating-an-asar-archive-as-a-normal-file

**Comment by jostrander** [comment]
I did read up on that, and I'm not having any immediate issues with an `asar` version of the build. Do you have any examples of things that would fail with the `fs` module? The example you linked to is showing that `original-fs` is needed only to read the `asar` file instead of its contents. However it did cause windows to fail to build because it couldn't grab something with the keyboard hooks.

**Comment by jostrander** [comment]
Also I believe there are some npm modules that are being packed into the resources folder that don't need to be, but the only way I've seen that fixed is by having two package.json files. One for development, and one for building.

**Comment by MarshallOfSound** [comment]
@jostrander We have `prune` set to `true` so no development npm modules are being included in the package

**Comment by jostrander** [comment]
Yep what I was seeing was the optional deps Debian and redhat packager npm packages in the resources directory. If that's the only few that make it in I'm not so concerned about it.

**Comment by BrianAllred** [comment]
@jostrander The files are much preferred. That keeps the user from having to install dpkg and rpmtools as build dependencies.

**Comment by tf2manu994** [comment]
@jostrander Just letting you know that circleci didn't like that last commit

**Comment by jostrander** [comment]
Yeah I saw, haven't had time to fix it. I might have to implement some kind of flag system to figure out what needs to build and when, because currently make:linux rebuilds 4 times due to dependencies for each 32 and 64 and deb and rpm. Will look into it soon.

**Comment by MarshallOfSound** [comment]
If you use `gulp` "requires" syntax correctly it should only build linux 32bit once and 64bit once.  Gulp has magical ways of determining task dependencies.  If you set it up right it handles it all for you @jostrander

**Comment by jostrander** [comment]
Yeah I know, it did figure out quite a bit, but there are still 4 builds unfortunately, compared to the 16 I calculated.  The last thing I tried to commit was zipping up the unpacked folders, but zip was throwing an error so I'll have to test that some more.

**Pull request closed without merging**
