### PR TITLE
about-tab: Add a About tab to the Settings page.

### PR DESCRIPTION
**Pull request by jjerome00**
I can never figure out the version of the app installed on my computer.  I decided add it as a tab in the Desktop Settings section.  After getting it in there, it seemed simple enough that it might be worth sharing.

I'm rather new to React, but I was able to figure out the pattern from other parts of the code.  I'm also rather new to open source PR's so I apologize in advance if I missed something.

settings dialog

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@jjerome00 Cheers for the PR, this feature already exists from the tray menu however.

`Menu --> Help --> About`

It will launch a dialog which contains exactly the information in this new tab 😄

**Comment by MarshallOfSound** [comment]
> I'm rather new to React, but I was able to figure out the pattern from other parts of the code. I'm also rather new to open source PR's so I apologize in advance if I missed something.

FWIW you nailed to code 👍 💯

**Comment by jjerome00** [comment]
Wow, I saw the `AboutModal` in the code but for the life of me I could not figure out where it was in the app.  I'd still recommend adding the version somewhere within the main application window, but I won't push it.  Thanks for the feedback!

**Comment by MarshallOfSound** [comment]
> I'd still recommend adding the version somewhere within the main application window

Where would you suggest putting it, I've played with putting it in the player window before (instead of a modal) but wherever I put it, it just took up to much space 😆

**Comment by jjerome00** [comment]
Originally I thought if there was an About tab, you could add whatever information you wanted.  This is why I just straight-up copied the AboutModal contents.

However, there are a few spots with a little bit of space:
* The `SettingsPage` header, justified on the right
* The bottom of the hamburger menu, with a light font

I've attached a couple of very rough examples.  Maybe they'll give you some ideas.  Thanks for taking the time to listen!

settings dialog with version

hamburger-menu

**Pull request closed without merging**
