### PR TITLE
UPDATE link to listenbrainz profile

### PR DESCRIPTION
**Pull request by sadlittlejoe**
UPDATE link to listenbrainz profile from https://listenbrainz.org/user/info -> https://listenbrainz.org/profile/

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
There is a conflict 😢

**Comment by dainguyenhuu** [comment]
:| Dont know what to do

**Comment by tf2manu994** [comment]
@sadlittlejoe the easiest solution is to make it again.

**Comment by sadlittlejoe** [comment]
Yep, will do

**Pull request closed without merging**
