### PR TITLE
Debounce forward/previous on the emitter to prevent double skipping

### LINKED ISSUE #2364: Make W10 Media Service actually usable
OS: Win10

Issue Descriptions: Media Keys skip twice if W10 Media Service is enabled.

Steps to Reproduce: Enable W10 Media Service, push an actual media key

According to previous Issues you implemented a "fix" so that media keys don't double-skip tracks. 

Apparently that fix was to disable the W10 Media Service. But I'd actually like to be using that, this seems more of a workaround then an actual fix. Because the error reappears if I use the W10 Media Service popup.

### PR DESCRIPTION
**Pull request by jostrander**
Maybe fixes #2364. Test before merging.

### CODE REVIEW

**Comment by BrianAllred** [comment]
Just curious, but wouldn't all button presses benefit from debouncing?

**Comment by jostrander** [comment]
They probably would, however I didn't specifically have complaints about those so I figured "if it ain't broke don't fix it".

**Comment by alok-sin** [comment]
@jostrander the play/pause also has this issue. But it's erratic. Perhaps debouncing will apply to that.

**Comment by jostrander** [comment]
Can anyone with the issue at hand confirm this fixes it for double skipping before I implement play/pause as well?

**Comment by MarshallOfSound** [comment]
@jostrander If you add play/pause I'll just merge it 😄

**Comment by PickNChew** [comment]
Does not seem to work. Still double skips.

**Comment by jostrander** [comment]
Added play/pause. As a side note, the pre-commit hooks don't work.

**Comment by crstnio** [comment]
I applied this patch and play/pause doesn't work at all for me.

Having an issue #3155 with Apple EarPods immediately starting play after pausing.

**Pull request closed without merging**
