### PR TITLE
Added shadow to lyrics display

### PR DESCRIPTION
**Pull request by MCManuelLP**
This adds shadows above the top and bottom of the lyrics div so that it's not cut off flat.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Can you please upload a screenshot of this, I am not sure exactly what this is going to look like and my git is screwed at the moment so I can't add remotes

**Comment by MCManuelLP** [comment]
Yeah sure, here you go.
screenshot-2016-04-06-08-36-41

**Comment by MarshallOfSound** [comment]
Ahh, nice, that looks good.  I wasn't sure what you meant by shadow but it kinda makes sense now :+1: 

LGTM :+1:   Just waiting on a circleci rebuild

**Comment by MarshallOfSound** [comment]
Oooh, hold up, the commit log is quite funky here.  Can we take the changes and rebase onto master.  Somehow one of my commits ended up here.  Looks like you broke a merge somewhere

**Comment by MCManuelLP** [comment]
There we go, all fixed.

**Pull request merged**
