### PR TITLE
reimplement last.fm scrobbling

### PR DESCRIPTION
**Pull request by petuhovskiy**
watch playback time and scrobble when it reaches 60% of song duration

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
The logic you have changed to internally makes little sense to me.

Can you please explain it either on GitHub or in comments.  For instance the whole `progress > 0 && progress < 2000` logic makes literally no sense 😕

**Comment by MarshallOfSound** [comment]
And FWIW the song should scrobble when it reaches `50%` which is what it already does so I'm not sure what this PR actually changes???

**Comment by petuhovskiy** [comment]
'change:playback-time' event fires every ~200ms, so it handles manual position change, when progress too big or negative

**Comment by petuhovskiy** [comment]
currently you can alternately click on the start and end positions of song every 10 seconds and it will increase scroblles count, what is not supposed to be

**Comment by MarshallOfSound** [comment]
I tested this out with other players that support last.fm and the current behavior appears to be conistent with their implementation so I'm going to close this as invalid.

Thanks for the PR though 👍

**Pull request closed without merging**
