### PR TITLE
Added French translation.

### PR DESCRIPTION
**Pull request by emilecantin**

### CODE REVIEW

**Comment by SolarLiner** [comment]
So you're from Québec :p 

I haven't found any good words for "issues". It's not only restricted to bugs, it includes feature improvements and other discussions that don't start from a mis-behavior. Neither "bugs" nor "problèmes" do the translation justice. "Feedback" would be closer I guess.  

Attached is a merge of our two files: 
[FR-fr.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/266389/FR-fr.zip)

**Comment by emilecantin** [comment]
Yes, how did you guess? 😄 

I had a hard time with it too, in the end, I just used "Problèmes" and kept going. I guess we could also use "Problèmes / Suggestions".

I'll have a look at your merged file shortly.

**Comment by SolarLiner** [comment]
I'd rather see and ampersand instead of a slash, but that's personal preference. Other than that, I'd say the translation is ready.

**Comment by MarshallOfSound** [comment]
@emilecantin @SolarLiner Can I just get a comment below with ":+1:" if you think this locale PR is all set to go

**Comment by SolarLiner** [comment]
@MarshallOfSound which one, the merged one I linked or the original one from Emile?

**Comment by MarshallOfSound** [comment]
@SolarLiner The one that is currently in the PR

**Comment by SolarLiner** [comment]
@MarshallOfSound well then it's not, my second upload is

**Comment by MarshallOfSound** [comment]
Please rebase and I will merge

**Comment by SolarLiner** [comment]
@emilecantin if you could update the PR with the updated FR-fr.json file (maybe you can keep yours as FR-ca.json ?)

**Comment by MarshallOfSound** [comment]
Closing PR due to how out of date it is and lack of response.  If @SolarLiner wants to pick this up I'll gladly accept a new clean PR

**Pull request closed without merging**
