### PR TITLE
If a WebSockets API method call returns a promise, resolve that promise before returning a result.

### LINKED ISSUE #1641: WebSocket Playback API has an empty return value for methods that invoke promises
**OS:**
Ubuntu 16.04

**Steps to Reproduce:**
   `{
      'namespace': 'search',
      'method': 'performSearch',
      'arguments': ['test search'],
      'requestID': 2
    }`
Sending the above message gives this result:
`{ namespace: 'result', requestID: 2, type: 'return', value: {} }`

GPMDP might need to make an effort to resolve promises and return through WebSockets only then.

### PR DESCRIPTION
**Pull request by arilotter**
Resolves #1641

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
RIP

Already fixed in c89b30f3b0822463bc2dc12b8bf621005db76b3f

Didn't realize you were going for the fix 😆

**Comment by arilotter** [comment]
LOL, thanks for fixing it! I like your solution better anyways :+1:

**Comment by MarshallOfSound** [comment]
The only real difference is mine handles promise rejection as `error` responses.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/c89b30f3b0822463bc2dc12b8bf621005db76b3f#diff-a4cddee37a18c64bce654445aaa81e58R105

Out of interest, what are you using the API for 👍 ?

**Comment by arilotter** [comment]
I'm building a dorm room automation system & automating GPMDP with voice commands from a remote device! Is there somewhere I could have a quick chat with you about another thing that might not need its own Issue?

**Comment by MarshallOfSound** [comment]
@arilotter Jump on Gitter, I'm always around 👍

**Pull request closed without merging**
