### PR TITLE
Use a configurable user agent to circumvent the sign in issue

### PR DESCRIPTION
**Pull request by ervinb**
Fixes https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3545

### CODE REVIEW

**Comment by WillPresley** [comment]
For what it's worth, this seemed to break Chromecast support for me. The icon was missing, and so was the 'extra' Miniplayer button. Going back to the nightly build from June 12th brought everything back without an issue, just thought I'd report the issue.

**Comment by eturk1** [comment]
where can we get a beta .exe for Windows to test out sign fix? :)

**Comment by MarshallOfSound** [comment]
@WillPresley Good catch, I think we need the fake user agent to include the "Chrome" string that the Chrome browser has. Can you test that by modifying your local settings file?

**Comment by WillPresley** [comment]
@MarshallOfSound That seemed to work. Copied my own UA from latest Chrome on Windows: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36` then pulled out the Windows-specific parts to leave just this: `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36` and the Chromecast features and bigger miniplayer button are back to normal.

**Comment by That-Marketing-Guy** [comment]
> Fixes #3545

How is this suppose to be a fix for a general user???

**Pull request merged**
