### PR TITLE
feature/spanish locale update

### PR DESCRIPTION
**Pull request by n4k1**

### CODE REVIEW

**Comment by fmayoral** [comment]
As translation goes It'll be ok once the missing tilde is fixed.
As the PR goes, please add a description to it, and squash the commits into a single commit so you don't pollute the tree  (check [How to squash commits in git after they have been pushed?](http://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed))
Also, consider contributing to `src/_locales/_provider.js` with spanish locale codes for windows equivalents (example [here](https://github.com/fmayoral/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/6e707787bd715cc5bf7b734bcd53c265076e6c12)), but you might want to get @MarshallOfSound opinion on this first ;)

**Comment by MarshallOfSound** [comment]
@fmayoral RE squishing I no longer require users to do it as I can do it from the GitHub PR interface (there is a squash and merge button) which is super useful 👍 

Please do add the spanish equivalents in `_provider`

**Comment by MarshallOfSound** [comment]
Please rebase and I will merge

**Comment by MarshallOfSound** [comment]
Closing PR due to how out of date it is.  If you rebase your branch onto `v4` and add the missing translations I'll gladly accept

**Pull request closed without merging**
