### PR TITLE
Change 'theme enabled' to 'dark theme'

### PR DESCRIPTION
**Pull request by tf2manu994**
Makes it easier for users to know what the hell it does

[Review on Reviewable](https://reviewable.io/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/246)

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Can we like, squash these into one commit "Fixed grammatical errors in desktop settings"

Thanks

**Comment by tf2manu994** [comment]
Sorry, I'm new to github, how do I do that

**Comment by MarshallOfSound** [comment]
Just google search

"squash git commits to single commit"

or 

"how to rebase in git"

**Comment by tf2manu994** [comment]
i think i did it?

**Pull request closed without merging**
