### PR TITLE
Bump ytmusic.js

### PR DESCRIPTION
**Pull request by renatolond**
This fixes gpmdp not detecting that a song is playing, #3920

### CODE REVIEW

**Comment by cfsmp3** [comment]
@renatolond it doesn't seem to fix the key problem for me though (linux)

**Comment by renatolond** [comment]
@cfsmp3 seems to have solved it over here, I have multimedia keys and song titles back (arch linux here)

**Comment by aidan-24com** [comment]
I would love this to be merged in if it does indeed fix the media key issue. here's hoping

**Comment by francislavoie** [comment]
Are there any build artifacts I can grab for linux (.deb) so I can use this in the meantime? Don't really feel like trying to set up a build env :grimacing:

**Comment by cfsmp3** [comment]
> Are there any build artifacts I can grab for linux (.deb) so I can use this in the meantime? Don't really feel like trying to set up a build env grimacing

Sure. It does not work for me but maybe I have a different problem on top of this. 
the .deb is too large for GitHub so here you go: 

https://drive.google.com/file/d/1w-DlXwhlbYdPhEJzLKxUHbKQmv4vfnJF/view?usp=sharing

**Comment by trobrock** [comment]
What does it take to get this merged? How can I help?

**Review by jostrander — APPROVED** [review]

**Comment by trobrock** [comment]
Thanks @jostrander is the release process automated or does a new version need cut manually?

**Comment by jostrander** [comment]
The release process is _very_ manual unfortunately and I have no access to the signing keys, so the repository owner will have to do a release, which tbh is unlikely to happen.

**Comment by trobrock** [comment]
@jostrander bummer.

**Comment by bruno-brant** [comment]
Hey @jostrander, why is it unlikely? Is @MarshallOfSound unfortunately too busy nowadays and no longer active in this project?

I'm grateful for all the work you guys have done here - GPMDP is a essential software to me and I would hate to see it fade away.

**Comment by Deloww** [comment]
> This fixes gpmdp not detecting that a song is playing, #3920

**Comment by Deloww** [comment]
> This fixes gpmdp not detecting that a song is playing, #3920

**Pull request merged**
