### PR TITLE
Add history navigation (back/forward, like in browser)

### PR DESCRIPTION
**Pull request by dennislysenko**
Didn't see an immediately noticeable option for this so I went ahead and added it for personal use. Feel free to merge if desired :)

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@dennislysenko There are already a wide varierty of ways to navigate forward / backward

* Alt + Left/Right
* Backspace
* Mouse Button 4 + 5
* 3 Finger swipe (OS X)
* UI "back" button

From my understanding of things the "Alt + Left/Right" shortcuts are the browser forward/backward standards so I think we should stick with those.

**Comment by dennislysenko** [comment]
@MarshallOfSound thanks for informing. Not sure which platform you are on, but Alt+Left/Right is not the browser standard on OSX. It is cmd+left/right. Perhaps you could include this as an OS-specific default?

**Comment by dennislysenko** [comment]
Also, if you inject the UI back button manually, in my opinion it would be easier to find if it were to the left of the search icon, or somewhere more to the left. Just a thought, as I had no thought to even look there :)

**Comment by MarshallOfSound** [comment]
@dennislysenko That's interesting, the `Alt + Left/Right` is standard on Linux and Windows.  It's strange that OS X would implement it differently (Round of applause for apple not following standards).

If you changed this PR to add a check to `e.metaKey` [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/fd3ffe17a2228b929c7307bf0a00eedfcedab199/src/inject/GPMInject/interface/customUI.js#L187) I would accept it.

Something like

```js
      || (e.which === 37 && (e.altKey || e.metaKey) && document.activeElement.value === undefined)) {
      attemptBack();
    } else if (e.which === 39 && (e.altKey || e.metaKey) && document.activeElement.value === undefined) {
```

Just check that is works and PR it here. :+1:

**Comment by dennislysenko** [comment]
I tried and... well, I only wish it were that simple. Unfortunately, as detailed [here](http://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript), the cmd key is not processed as a modifier, for whatever boneheaded reason, but as a separate keypress. e.metaKey does not ever appear to be true, as the command and the arrow register as two separate keypresses.

**Comment by dennislysenko** [comment]
In fact, the arrow key only registers as `keydown`, not `keyup`.

**Comment by jostrander** [comment]
Just so you don't get too far into your research, @marshallofsound already
has all of that figured out, about the meta key not working on keyup etc.
Just trying to find a solution. Not sure which issue he has that on or if I
read it in gitter.

**Comment by dennislysenko** [comment]
@jostrander thanks for the update. I actually do have it working perfectly now, so if you wish, I can clean up the code to fit the pre-commit hooks and submit a pull request. Let me know, @MarshallOfSound :)

**Comment by MarshallOfSound** [comment]
@dennislysenko PR it and I'll take a look :+1:

**Pull request closed without merging**
