### PR TITLE
Exchanged Tray Icon for official GPM "Favicon"

### PR DESCRIPTION
**Pull request by berryelectronics**
Swapped the Tray Icon for OSX out to the small GPM Favicon, no more Dorito & LP.
Thought it might be good to change the Tray Icon for the other OS's aswell, to make it more uniformly.

I did compiled it once and worked. I didnt really changed something drastically, so there shouldnt be any problem with compiling, really :D .

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Can we please delete the old `macTemplate.png` and include the original `svg` file in this PR

**Comment by berryelectronics** [comment]
It was only used for the tray? Wasnt sure about that. will do it.

**Comment by MarshallOfSound** [comment]
@berryelectronics You can verify by just doing a project wide search in your IDE for `macTemplate` and see what is returned

**Comment by berryelectronics** [comment]
Whats about maxTemplate@2x /5x? Should they stay?

**Comment by MarshallOfSound** [comment]
@berryelectronics Those should be recreated with the same dimensions but using the new image

**Comment by MarshallOfSound** [comment]
@berryelectronics You also need to edit your `macTemplate` icons so that the music note is transparent.  Otherwise it becomes black on `OS X`

**Comment by MarshallOfSound** [comment]
You can do this by editing and converting the SVG correctly

**Comment by berryelectronics** [comment]
on the `macTemplate.png` it should be transparent. But not on the other one (forgot that).

**Comment by berryelectronics** [comment]
Note: For the normal tray logo the note isnt transparent. I found that it looked weird.

**Comment by MarshallOfSound** [comment]
LGTM :+1:

**Pull request merged**
