### PR TITLE
Grammatical fixes

### PR DESCRIPTION
**Pull request by tf2manu994**
[Review on Reviewable](https://reviewable.io/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/255)

### CODE REVIEW

**Comment by tf2manu994** [comment]
lets see if i can stop screwing up git!

**Comment by MarshallOfSound** [comment]
Seems simple enough thanks!

**Comment by tf2manu994** [comment]
Yay I feel like I did something somewhat useful!

**Comment by MarshallOfSound** [comment]
You made the list :+1:  --> https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/graphs/contributors

**Pull request merged**
