### PR TITLE
Fixed readme.md

### PR DESCRIPTION
**Pull request by tf2manu994**
kay lets see if this works

[Review on Reviewable](https://reviewable.io/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/322)

### CODE REVIEW

**Comment by tf2manu994** [comment]
oh for fucks sake

can someone teach me how to add stuff to te other pull request

**Comment by MarshallOfSound** [comment]
Cherry pick?

**Comment by tf2manu994** [comment]
what?

i tried adding stuff and this doesnt seem to work

**Comment by MightyPork** [comment]
@tf2manu994 you are supposed to fork a repo, then make a feature branch, eg. 

```bash
git checkout -b fix-typo
```

then do your thing on that branch and make a PR from that branch.
If you push to the branch again, it will be automatically added to the PR.

And of course this let's you make multiple PR's from a single fork.

You can then update your master from upstream like this:

```bash
# go to master
git checkout master

# add upstream as a remote
git remote add upstream <address to upstream>

# pull & merge changes from upstream
git pull upstream master
```

**Comment by MarshallOfSound** [comment]
@tf2manu994 Any progress on the squishing / handling this PR

**Pull request merged**
