### PR TITLE
Adding app-wide custom theme and system theme mode (Vista & up)

### PR DESCRIPTION
**Pull request by SolarLiner**
- Added support for Windows Vista/7/8/10 system colors (returns Accent.Lime700 for XP and below)
- Listening to theme changes
- Custom accent color now applies to the whole application.

The algorithm to pick the closest accent color from the chosen one is to be looked at again, but works alright.  
I initially forked to separate the dark theme from the custom theme (allowing to change the color of the light theme too) but in the end I dropped it.

Also, controls do not immediately repaint when changing colors (from wheel or from system change). Looking into it, but not finding anything as of right now.

Preview GFY: https://gfycat.com/PinkTepidBarnowl

[Review on Reviewable](https://reviewable.io/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135)

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Will look over this in detail later (at work at the moment) but before I do could you quickly change the few bits of french throughout the files to english, better to keep language consistent throughout the files and will make it easier for me to see whats going on.

Cheers

**Comment by MarshallOfSound** [comment]
Also there are a bunch of merge conflicts

**Comment by MarshallOfSound** [comment]
Review status: 0 of 27 files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[Google Play Music.Bootstrapper/Google Play Music.Bootstrapper.wixproj, line 13 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7Qe8QE3SMo2OlfqD9A:-K7Qe8QE3SMo2OlfqD9B:-1703289488) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music.Bootstrapper/Google Play Music.Bootstrapper.wixproj#L13)):*
Lets remove this, it does nothing

---

*[Google Play Music.Bootstrapper/Google Play Music.Bootstrapper.wixproj, line 63 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QeGuJhZlxyZnbtA4A:-K7QeGuJhZlxyZnbtA4B:2027339736) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music.Bootstrapper/Google Play Music.Bootstrapper.wixproj#L63)):*
We can remove this target as it goes against Automatic Package Restore

https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore

---

*[Google Play Music.Installer/Google Play Music.Installer.wixproj, line 13 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7Qaw4n4DSfpYp0NRcJ:-K7Qaw4n4DSfpYp0NRcK:90738188) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music.Installer/Google Play Music.Installer.wixproj#L13)):*
This addition is pointless, please remove

---

*[Google Play Music.Installer/Google Play Music.Installer.wixproj, line 91 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QbIG9Pg9yGxDqYs4m:-K7QbIGALcPrWN3zuvxY:1685421174) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music.Installer/Google Play Music.Installer.wixproj#L91)):*
This target should be removed as it goes against the Automatic Package Restore spec

https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore

---

*[Google Play Music.Installer/packages.config, line 3 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QbVJNNJjhe3XXC1Ga:-K7QbVJNNJjhe3XXC1Gb:1568108930) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music.Installer/packages.config#L3)):*
Really? We need this on an installer?

---

*[Google Play Music/CEF Modules/DragHandler.cs, line 9 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QbmUqotKPB61Hc_Dr:-K7QbmUqotKPB61Hc_Ds:1305512715) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/CEF Modules/DragHandler.cs#L9)):*
Why was this added in this PR, this is overflowing the scope a bit?

---

*[Google Play Music/CEF Modules/DragHandler.cs, line 11 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QbqnVcZ02SgRX0XMp:-K7QbqnVcZ02SgRX0XMq:-1962570285) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/CEF Modules/DragHandler.cs#L11)):*
Instead of comment it out can we put a comment here explaining why we need to do nothing in this method

---

*[Google Play Music/CEF Modules/MenuHandler.cs, line 28 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7Qbwi-KJZogc5YwM6F:-K7Qbwi-KJZogc5YwM6G:1726326424) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/CEF Modules/MenuHandler.cs#L28)):*
Again, why is this method added in this PR.  Overflowing scope a little bit?

---

*[Google Play Music/CEF Modules/MenuHandler.cs, line 30 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7Qc0TYDooHPC1SHMse:-K7Qc0TYDooHPC1SHMsf:-1095131384) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/CEF Modules/MenuHandler.cs#L30)):*
Guess?  Check the CefSharp source file, they normally have great commenting

https://github.com/cefsharp/CefSharp/blob/b04ccbb26956ecd21c61f273591ea2064d4b03b5/CefSharp/IContextMenuHandler.cs#L46

In this case I think we should be returning true, but it comes back to the above comment.  Why are we putting this method in

---

*[Google Play Music/CoreMusicApp.cs, line 44 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QcOrKNecXUONX7zaY:-K7QcOrKNecXUONX7zaZ:-451604159) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/CoreMusicApp.cs#L44)):*
Can we get rid of these 2 extra line returns

---

*[Google Play Music/CoreMusicApp.cs, line 192 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QcY8PgxYuI5L81UZx:-K7QcY8PgxYuI5L81UZy:-21866057) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/CoreMusicApp.cs#L192)):*
Due to the bump in CEF version we no longer need to wrap JS in a self executing function for it to work.  Check out the example elsewhere in the updated code

---

*[Google Play Music/CoreMusicApp.cs, line 208 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QciGOm7Sd8RBKBF9-:-K7QciGOm7Sd8RBKBF90:-153102387) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/CoreMusicApp.cs#L208)):*
Can we remove the commented out code.  If we don't need it, it should be gone completely

---

*[Google Play Music/Google Play Music.csproj, line 323 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7Qcy_CPxcunoMyA0vU:-K7Qcy_CPxcunoMyA0vV:-1722837529) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/Google Play Music.csproj#L323)):*
This target should not be here as per the previous comment about Automatic Package Restore

---

*[Google Play Music/Properties/Settings.Designer.cs, line 3 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7Qd8YQas7E-XK-8x_B:-K7Qd8YQas7E-XK-8x_C:-1070118105) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/Properties/Settings.Designer.cs#L3)):*
French back to english please

---

*[Google Play Music/Resources/JS/dark-theme.js, line 187 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QdDPf78fN3XUP8mpv:-K7QdDPf78fN3XUP8mpw:-2119863230) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/Resources/JS/dark-theme.js#L187)):*
This entire file is deleting in master, this really needs to be rebased :cactus: 

---

*[Google Play Music/Settings.cs, line 1 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QdMQGMX2Os3NbgYbc:-K7QdMQGMX2Os3NbgYbd:680367281) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/Settings.cs#L1)):*
Is it just me, or does the file not actually do anything?

---

*[Google Play Music/Settings.cs, line 4 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QdIeGXc31fPsqMDHW:-K7QdIeGXc31fPsqMDHX:672283902) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Google Play Music/Settings.cs#L4)):*
French to english please

---

*[Material Skin/MaterialSkin.csproj, line 15 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QdbYuzkHwgcizhlE4:-K7QdbYuzkHwgcizhlE5:-30646310) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Material Skin/MaterialSkin.csproj#L15)):*
Can we get rid of this, it does nothing

---

*[Material Skin/MaterialSkin.csproj, line 114 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7Qdet23RAHnPafHEMY:-K7Qdet23RAHnPafHEMZ:759315778) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/Material Skin/MaterialSkin.csproj#L114)):*
Another target that has to be removed or Automatic Package Restore won't work

---

*[UnitTests.Test/UnitTests.Test.csproj, line 14 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QdkgfZL2gvaIC2mbt:-K7QdkgfZL2gvaIC2mbu:62134369) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/UnitTests.Test/UnitTests.Test.csproj#L14)):*
Again, lets remove this

---

*[UnitTests.Test/UnitTests.Test.csproj, line 110 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7Qdn5t5ehzMERlVYf3:-K7Qdn5t5ehzMERlVYf4:1400363174) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/UnitTests.Test/UnitTests.Test.csproj#L110)):*
This target should be removed for Automatic Package Restore

---

*[UnitTests.Test/UtilsTest.cs, line 1 \[r1\]](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-K7QdtRdg3pT4V1zJITs:-K7QdtRdg3pT4V1zJITt:1016554381) ([raw file](https://github.com/marshallofsound/google-play-music-desktop-player-unofficial-/blob/27fb47f9aa85f4c376783edf42215b4aacd00fe8/UnitTests.Test/UtilsTest.cs#L1)):*
Yay!
Tests!!!!

Love it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135)*

**Comment by MarshallOfSound** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135)*

**Comment by SolarLiner** [comment]
The only projects I modified code in are Google Play Music and
MaterialSkin. I suspect the rest was changed by VS2015, and the French
parts because of the language of the IDE.

I'm looking into it ASAP.

Le jeu. 7 janv. 2016 11:39, Samuel Attard <notifications@github.com> a
écrit :

**Comment by SolarLiner** [comment]
In fact, pretty much all of the first commit can go. This was all generated from Visual Studio as it was resolving issues.
The remaining French file is when I added the UseCustomColor entry, which I will redo once I switch VS to English.

**Comment by MarshallOfSound** [comment]
Also of note now is the new Contributing.md   Might want to check that out, for one thing the commits you PR should be squashed please :smile: 

---

Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/marshallofsound/google-play-music-desktop-player-unofficial-/135#-:-K7SYh-z-kGD_okB2oon:-1861370759)*

**Comment by MarshallOfSound** [comment]
Closing due to progress on #171

**Pull request closed without merging**
